# Generated by Django 4.2 on 2024-04-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("prenom", models.CharField(max_length=128)),
                ("nom", models.CharField(max_length=128)),
                ("date_naissance", models.DateField(verbose_name="Date de naissance")),
                ("courriel", models.EmailField(max_length=254, unique=True)),
                (
                    "mail_secondaire",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        unique=True,
                        verbose_name="Email Secondaire",
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Numéro de téléphone",
                    ),
                ),
                (
                    "adresse",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="Adresse"
                    ),
                ),
                (
                    "pays",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="Pays"
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="Région"
                    ),
                ),
                (
                    "code_postal",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Code Postal",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
