# Generated by Django 4.2 on 2024-05-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="courriel",
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
