# Generated by Django 4.2 on 2024-05-20 01:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_usermodel_is_staff_alter_usermodel_courriel"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usermodel",
            options={"verbose_name": "Utilisateur"},
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="courriel",
            field=models.EmailField(
                error_messages={"unique": "Ce courriel est déjà utilisé."},
                max_length=255,
                unique=True,
            ),
        ),
    ]
