# Generated by Django 4.2 on 2024-04-29 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantite",
                    models.IntegerField(default=1, verbose_name="Nombre d'article"),
                ),
                (
                    "statusCommande",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente de traitement"),
                            ("en_cours", "En cours de livraison"),
                            ("livre", "Livré"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Categorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="Produit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=128)),
                ("description", models.TextField()),
                ("marque", models.CharField(max_length=128)),
                ("prix", models.FloatField()),
                (
                    "stock",
                    models.IntegerField(default=0, verbose_name="Quantité disponible"),
                ),
                ("slug", models.SlugField(blank=True, max_length=128)),
                (
                    "categorie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shop.categorie",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Panier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente de traitement"),
                            ("en_cours", "En cours de livraison"),
                            ("livre", "Livré"),
                        ],
                        max_length=100,
                    ),
                ),
                ("dateCommande", models.DateTimeField(blank=True, null=True)),
                ("articles", models.ManyToManyField(to="shop.article")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImageProduit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=128)),
                ("image", models.ImageField(upload_to="images_prod")),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="shop.produit",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="article",
            name="produit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="shop.produit"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
