# Generated by Django 4.2 on 2024-04-24 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Produit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=128)),
                ("description", models.TextField()),
                ("marque", models.CharField(max_length=128)),
                ("reference", models.CharField(max_length=128)),
                ("prix", models.FloatField()),
                (
                    "stock",
                    models.IntegerField(default=0, verbose_name="Quantité disponible"),
                ),
                ("categorie", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="ImageProduit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images_prod")),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="shop.produit",
                    ),
                ),
            ],
        ),
    ]
