# Generated by Django 4.2 on 2024-04-29 14:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="imageproduit",
            name="nom",
        ),
    ]
