# Generated by Django 4.2 on 2024-04-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="produit",
            name="slug",
            field=models.SlugField(default="lus", max_length=128),
            preserve_default=False,
        ),
    ]
