# Generated by Django 4.2 on 2024-04-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_remove_imageproduit_nom"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageproduit",
            name="nom",
            field=models.CharField(default=" ", max_length=128),
            preserve_default=False,
        ),
    ]
