# Generated by Django 4.2 on 2024-04-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_imageproduit_nom"),
    ]

    operations = [
        migrations.AddField(
            model_name="produit",
            name="star",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="produit",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
