# Generated by Django 4.2 on 2024-04-29 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0004_produit_star_alter_produit_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produit",
            name="star",
            field=models.IntegerField(
                blank=True,
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
