# Generated by Django 4.2 on 2024-05-01 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shop", "0005_alter_produit_star"),
    ]

    operations = [
        migrations.AlterField(
            model_name="panier",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="produit",
            name="slug",
            field=models.SlugField(blank=True, max_length=128, unique=True),
        ),
    ]
