# Generated by Django 4.2 on 2024-05-03 23:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shop", "0006_alter_panier_user_alter_produit_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="statusCommande",
        ),
        migrations.RemoveField(
            model_name="panier",
            name="dateCommande",
        ),
        migrations.RemoveField(
            model_name="panier",
            name="status",
        ),
        migrations.AddField(
            model_name="article",
            name="dateCommande",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="statutCommande",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="article",
            name="quantite",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(2),
                ],
                verbose_name="Nombre d'article",
            ),
        ),
        migrations.AlterField(
            model_name="panier",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="produit",
            name="stock",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Quantité disponible",
            ),
        ),
    ]
