# Generated by Django 4.2 on 2024-05-04 18:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0007_remove_article_statuscommande_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="quantite",
            field=models.IntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Nombre d'article",
            ),
        ),
        migrations.AlterField(
            model_name="panier",
            name="articles",
            field=models.ManyToManyField(blank=True, to="shop.article"),
        ),
    ]
