# Generated by Django 4.2 on 2024-05-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0008_alter_article_quantite_alter_panier_articles"),
    ]

    operations = [
        migrations.AddField(
            model_name="produit",
            name="ref",
            field=models.CharField(default="", max_length=128),
        ),
    ]
