# Generated by Django 4.2 on 2024-05-05 14:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0010_alter_produit_ref"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produit",
            name="ref",
        ),
    ]
