# Generated by Django 4.2 on 2024-05-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0011_remove_produit_ref"),
    ]

    operations = [
        migrations.AddField(
            model_name="produit",
            name="ref",
            field=models.CharField(default="", max_length=128),
        ),
    ]
