# Generated by Django 4.2 on 2024-05-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0012_produit_ref"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produit",
            name="ref",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
