# Generated by Django 4.2 on 2024-05-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0013_alter_produit_ref"),
    ]

    operations = [
        migrations.AddField(
            model_name="panier",
            name="frais",
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name="panier",
            name="taxes",
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
