# Generated by Django 4.2 on 2024-05-20 01:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0014_panier_frais_panier_taxes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"verbose_name": "Article"},
        ),
        migrations.AlterModelOptions(
            name="imageproduit",
            options={"verbose_name": "images"},
        ),
        migrations.AlterModelOptions(
            name="panier",
            options={"verbose_name": "Panier"},
        ),
        migrations.AlterModelOptions(
            name="produit",
            options={"verbose_name": "Produit"},
        ),
        migrations.AlterField(
            model_name="produit",
            name="star",
            field=models.IntegerField(
                blank=True,
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="notes",
            ),
        ),
    ]
